"""Initial Migration

Revision ID: 465a82af37c9
Revises: 
Create Date: 2026-03-02 09:33:14.659607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465a82af37c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_created_at', table_name='interviews')
    op.create_index('idx_user_created_at', 'interviews', ['user_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_created_at', table_name='interviews')
    op.create_index('idx_user_created_at', 'interviews', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
